### ISSUE TITLE
Security issue - contacts are stored unencrypted in the home directory

### ISSUE THREAD

**Issue by tomaskikutis** [flathub/org.gnome.Contacts#34]
Also discussed here https://gitlab.gnome.org/GNOME/gnome-contacts/-/issues/213

I expected that using flatpack version would fix it, but it does not. It stores unencrypted sqlite database file in the same folder in home directory that was used by deb version of the application.

**Comment by nielsdg** [comment]
Please actually read the comments there. Contacts doesn't know about a sqlite database (it's implemented by a different component) and if it would, it would not encrypt it.

**Comment by tomaskikutis** [comment]
Maybe I wasn't clear enough in the description. In this issue, I'm not asking for encryption, but to fix the flatpack version, so it is properly containerized and stores the database file inside its own container that would not be accessible to other applications without root privileges.

> Contacts doesn't know about a sqlite database

Which application is writing that database? evolution-data-server? Is it possible to configure it so that database ends up stored in the container?

**Comment by nielsdg** [comment]
> stores the database file inside its own container that would not be accessible to other applications without root privileges.

We can't store a database file, if we don't know about it :-)

On the other hand: I think you have a completely reversed understanding of formats like Flatpak: it will make sure the flatpak'ed application cannot just do anything on the host machine, ie escape it's sandbox, or at least not without user consent.

However, the reverse is still definitely possible: for example, you can just use `flatpak run --command=sh --devel $APP_ID` to get an interactive shell within the app's sandbox. In other words: any non-containerized application within your user session is still a possible attack vector. Don't run untrusted applications without using a proper container format.

> Which application is writing that database? evolution-data-server? Is it possible to configure it so that database ends up stored in the container?

Evolution-data-server could be the process that does this (I don't know the exact internals of that). However, e-d-s runs as a service on the host machine, and we just talk to it over D-Bus (it's actually one of the few holes we have to poke). In other words: still not something Contacts knows or cares about.
